---
title: "Exploración de datos sobre comparación de casquillos"
author: "Juan Sebastian Cely y Pedro Ravelo"
output: html_document
---

## Códigos
1 = Casquillo impreso

2 = Casquillo metálico
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include = FALSE}
library(tidyverse)
library(readxl)
library(knitr)
```


```{r data, include=FALSE}
Harnezing <- read_excel("Data_Bees_Survival.xlsx", sheet = 1)
Survival <- read_excel("Data_Bees_Survival.xlsx", sheet = 2)
```


```{r Exploring harnezing data, echo=FALSE}
# Boxplot for Type_Har

# Updating factor labels for Type_Har
Harnezing$Type_Har <- factor(Harnezing$Type_Har, levels = c(1, 2), labels = c("3D", "Metallic"))

# Boxplot for Type_Har with updated labels
Harnezing %>%
  ggplot(aes(x = Type_Har, y = Duration)) +
  geom_boxplot() +
  stat_summary(fun = "mean", geom = "point", shape = 18, size = 3, color = "red") + # Add mean
  labs(x = "Harnessing Tube",
       y = "Duration (s)") +
  theme_minimal(base_size = 14) +  # Clean theme, larger font
  theme(plot.title = element_text(hjust = 0.5)) # Center title

# Updating factor labels for Type_Har
Harnezing$Researcher <- factor(Harnezing$Researcher, levels = c(0, 1, 2), labels = c("A", "B", "C"))

# Filter data to only include Researchers A and B
Harnezing_filtered <- Harnezing %>%
  filter(Researcher %in% c("A", "B"))

# Boxplot for Researcher A and B
Harnezing_filtered %>%
  ggplot(aes(x = Researcher, y = Duration)) +
  geom_boxplot(outlier.shape = NA) + 
  stat_summary(fun = "mean", geom = "point", shape = 18, size = 3, color = "red") + 
  labs(x = "Researcher",
       y = "Duration (s)") +
  theme_minimal(base_size = 14) +
  theme(plot.title = element_text(hjust = 0.5)) # Center title

```


```{r Exploring survival data, message = FALSE, echo=FALSE}
time <- Harnezing %>%
  group_by(Type_Har) %>%
  summarize(x = mean(Duration))
max_life <- Survival %>%
  group_by(ID, Type_Har) %>%
  summarise(max_life = max(Feeding_day))
kable(max_life %>%
  group_by(Type_Har) %>%
  summarise(mean_days_alive = mean(max_life)), col.names = c("Casquillo", "Promedio supervivencia (días)"), caption = "Comparación del promedio de días de supervivencia para cada casquillo")
max_life$Type_Har <- factor(max_life$Type_Har, levels = c(1, 2), labels = c("3D", "Metallic"))
max_life %>%
  ggplot(aes(x = max_life, color = Type_Har)) +
  geom_density() +
  labs(x = "Number of days alive",
       y = "Distribution", color = "Harnessing tube") +
theme_minimal(base_size = 14)
```

```{r counting errors during harnezing process, echo=FALSE}

# Calculating number of errors
number_errors <- Harnezing %>% 
  mutate(yes_no_error = case_when(Error == 0 ~ 0, Error != 0 ~ 1)) %>%
  group_by(Type_Har) %>%
  summarize(total_errors = sum(yes_no_error))

# Bar plot for total errors by Type_Har (Harnessing Tube)
ggplot(number_errors, aes(x = Type_Har, y = total_errors, fill = Type_Har)) +
  geom_bar(stat = "identity", color = "black") +  # Bar plot with borders
  labs(x = "Harnessing tube",
       y = "Total number of errors") +
  theme_minimal(base_size = 14) +  # Clean theme with larger fonts
  theme(plot.title = element_text(hjust = 0.5)) +  # Center title
  scale_fill_manual(values = c("3D" = "#619CFF", "Metallic" = "#F8766D")) +  # Custom colors
  guides(fill = "none")  # Remove legend, since x-axis labels describe the data

```

